# Extracting ChatBot Online appointment Feedback data from mysql part-2

* Here are feedback where we found the user experience with there consultant doctor and save that data in phpmysql (complete data saved on events table in **doctor_appointment** database) using rasa file             endpoints.yml i.e.


* **tracker_store:** -> tracker store define in endpoints.yml file to store data during your conversation. 



* For further query go with this link-->[RASA_TRACKER_STORE](https://rasa.com/docs/rasa/api/tracker-stores/)


  
* We have to extract data from phpmyadmin through mysql.connector python library .



* Data of chatbot are in json format so we used json python library to read json data easily and to extract all     features.

  
* Last we used pandas library to create dataframe or append all necessary information which was extracted before.
  Select query are used to extracted all data from phpmyadmin database i.e."doctor_appointment".
  
  
* Where clause used in select query to extract data according to  **sender_id** columns which is define in table     **events** in database **doctor_appointment** so that we get always fresh data or runtime data not all             previously data which were seen before.We append the data in data variable later on we work on that data.

In [1]:

import mysql.connector
import json
from mysql.connector import Error
import pandas as pd

data=pd.DataFrame(columns=["event"])
try:
    connection =mysql.connector.connect(host='127.0.0.1',
					 database='doctor_appointment',
                                         user='root',
                                         password='')

    sql_select_Query = "select * from events"
    cursor = connection.cursor()
    cursor.execute(sql_select_Query)
    records = cursor.fetchall()
    for row in records:
        sess=row[1]
    sql_select_Query = "select * from events where sender_id='%s'"%sess
    cursor = connection.cursor()
    cursor.execute(sql_select_Query)
    records = cursor.fetchall()
    for row in records:
        conv=row[6]
        con=json.loads(conv)
        if(con["event"]=="user" or con["event"]=="bot"):
            
            chat_bot=pd.DataFrame(con)
            data=data.append(chat_bot,sort=True)
except Error as e:
    print("Error reading data from MySQL table", e)
finally:
    if (connection.is_connected()):
        connection.close()
        cursor.close()
        print("MySQL connection is closed")

MySQL connection is closed

# Now we have to see all the data  which was append before .

In [2]:
data

,data,event,input_channel,message_id,metadata,parse_data,text,timestamp
entities,NaN,user,socketio,5617bbc76a854653955f27b2f0f16aad,NaN,[],/get_started,1.573727e+09
intent,NaN,user,socketio,5617bbc76a854653955f27b2f0f16aad,NaN,"{'name': 'get_started', 'confidence': 1.0}",/get_started,1.573727e+09
intent_ranking,NaN,user,socketio,5617bbc76a854653955f27b2f0f16aad,NaN,"[{'name': 'get_started', 'confidence': 1.0}]",/get_started,1.573727e+09
text,NaN,user,socketio,5617bbc76a854653955f27b2f0f16aad,NaN,/get_started,/get_started,1.573727e+09
entities,NaN,user,socketio,891bab3ef4d0433aa33d83008ff968f0,NaN,[],hi,1.573727e+09
...,...,...,...,...,...,...,...,...
quick_replies,None,bot,NaN,NaN,NaN,NaN,Bye,1.573727e+09
buttons,None,bot,NaN,NaN,NaN,NaN,Bye,1.573727e+09
attachment,None,bot,NaN,NaN,NaN,NaN,Bye,1.573727e+09
image,None,bot,NaN,NaN,NaN,NaN,Bye,1.573727e+09
custom,None,bot,NaN,NaN,NaN,NaN,Bye,1.573727e+09

* Most of the features columns are unnecessary and some are null values,so our next approach is to filter all the data and extract all valuable or necessary data from them.
* Some data consist null value i.e. NaN (not a number) we remove it by using **dropna()** .

* For filtering our data we used **drop()** method of pandas library to drop the columns which are not necessary 
  for visualization .

In [3]:
data.dropna(how="any",axis=1,inplace=True)


# In[33]:


data.drop("timestamp",axis=1,inplace=True)


# In[34]:


data.drop(["entities","intent","intent_ranking","attachment","buttons","custom","elements","image"],inplace=True)


# In[35]:


data


# In[36]:

              event                                               text
text           user                                       /get_started
text           user                                                 hi
quick_replies   bot  Request to schedule an appointment with our ex...
quick_replies   bot                                 How May I Help You
text           user                                          /FeedBack
quick_replies   bot                   You are able to meet the doctor?
text           user                                         /YesOnTime
quick_replies   bot  How much time did you have to wait at the doct...
text           user                                            /Ontime
quick_replies   bot  Rate your appointment experience with the clin...
text           user                                                  5
quick_replies   bot  Can you please share your email address so tha...
text           user                                        abc@xyz.com
quick_replies   bot  Would you recommend Medi Health Care to your f...
text           user                                                yes
quick_replies   bot                                                Bye

# After dropping some columns we get three columns where,
1. one blank column which has rows like text and quick_replies,
2. next is event column which define conversation held between bot and user,where bot implies bot conversation or    asking some question to user or user are the given answer,
3. last columns define what conversation actually happen i.e

**a. hi(user text message hi)**


**b. Request to schedule an appointment with our ex...
How May I Help You(bot replies)**

In [4]:
data.T

,text,text,quick_replies,quick_replies,text,quick_replies,text,quick_replies,text,quick_replies,text,quick_replies,text,quick_replies,text,quick_replies
event,user,user,bot,bot,user,bot,user,bot,user,bot,user,bot,user,bot,user,bot
text,/get_started,hi,Request to schedule an appointment with our ex...,How May I Help You,/FeedBack,You are able to meet the doctor?,/YesOnTime,How much time did you have to wait at the doct...,/Ontime,Rate your appointment experience with the clin...,5,Can you please share your email address so tha...,abc@xyz.com,Would you recommend Medi Health Care to your f...,yes,Bye

**T implies Transpose in simple terms convert its rows to columns and vice-versa.**

In [5]:
user_data=data[data["event"]=="user"] 
print(user_data)

     event          text
text  user  /get_started
text  user            hi
text  user     /FeedBack
text  user    /YesOnTime
text  user       /Ontime
text  user             5
text  user   abc@xyz.com
text  user           yes

* **user_data** dataframe define only the user conversation.

In [6]:
ab=data.T
ab["text"]

,text,text,text,text,text,text,text,text
event,user,user,user,user,user,user,user,user
text,/get_started,hi,/FeedBack,/YesOnTime,/Ontime,5,abc@xyz.com,yes

* **Here user gave 5 rating  which he/she experice the meeting held with there consultant docter.
  We can improve this rating according to user responses in future which are benificial for both the parties**

In [7]:
from sqlalchemy import create_engine

# create sqlalchemy engine
engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                       .format(user="root",
                               pw="",
                               db="doctor_appointment"))


# In[70]:

data.reset_index()


data.to_sql('feedback_user', con = engine, if_exists = 'append', chunksize = 1000)